### PR TITLE
Tier1-group2-task2

### PR DESCRIPTION
**Pull request by DzSabina**

### CODE REVIEW

**Review by borisbradic — CHANGES_REQUESTED** [review]
Seems like you are missing 'bandit10'. Please check it.

**Comment by DzSabina** [comment]
> Seems like you are missing 'bandit10'. Please check it.

Thought 9>10 is the last level needed. Should be fixed now. Thank you, Boris!

**Comment by sqlheisenberg** [comment]
Looks good to me.
cc @borisbradic

**Review by sqlheisenberg — APPROVED** [review]

**Review by borisbradic — APPROVED** [review]
All good now!

**Pull request merged**
