### PR TITLE
Adding bash scripts for week-3 task

### PR DESCRIPTION
**Pull request by DzSabina**
Week-3 task Bash / Shell scripting

Chapter 13, Chapter 14, Chapter 15, and Chapter 16 scripts from the book Linux Command Line and Shell Scripting Bible, 3rd Edition

### CODE REVIEW

**Comment by DzSabina** [comment]
[ week3-screenshots.zip](https://github.com/DzSabina/sabina-dzino-devops-mentorship/files/10983922/week3-screenshots.zip)
Please see attached screenshots from script runs.

**Review by borisbradic — CHANGES_REQUESTED** [review]
Please.. 

Group scripts in directories which they should be part of, like: "chapter-13", "chapter-14", etc.. 
Try to do same with screenshots from the zip..

Then remove files which we don't need: output files or similar..

**Comment by DzSabina** [comment]
@borisbradic I organised the scripts and screenshots again and removed input and output files.
[ week3-screenshots-folders.zip](https://github.com/DzSabina/sabina-dzino-devops-mentorship/files/10990012/week3-screenshots-folders.zip)
Please have a look and let me know if it looks good now. Thank you!

**Comment by DzSabina** [comment]
@borisbradic I organised the scripts and screenshots again and removed input and output files.
[ week3-screenshots-folders.zip](https://github.com/DzSabina/sabina-dzino-devops-mentorship/files/10990012/week3-screenshots-folders.zip)
Please have a look and let me know if it looks good now. Thank you!

**Review by borisbradic — APPROVED** [review]

**Pull request merged**
